[project]
name = "rag-assistant"
version = "0.1.0"
description = "RAG AI Assistant"
authors = [
    { name = "mark", email = "mrnikerin@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "greenlet>=3.5.6",
]

[tool.uv.workspace]
members = ["shared", "ingestion_service", "assistant_service", "eval"]
