"""change embedding dimension to 1024 for local model

Revision ID: 5305e176f560
Revises: 9ff133efc39b
Create Date: 2026-09-23 01:11:41.485909

"""
from typing import Sequence, Union

import pgvector
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5305e176f560'
down_revision: Union[str, Sequence[str], None] = '9ff133efc39b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
               existing_nullable=True)
    op.drop_index(op.f('idx_chunks_active'), table_name='chunks', postgresql_where='(is_active = true)')
    op.drop_index(op.f('idx_chunks_content_trgm'), table_name='chunks', postgresql_ops={'content': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_chunks_embedding_hnsw'), table_name='chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw', postgresql_where='(is_active = true)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_chunks_embedding_hnsw'), 'chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw', postgresql_where='(is_active = true)')
    op.create_index(op.f('idx_chunks_content_trgm'), 'chunks', ['content'], unique=False, postgresql_ops={'content': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_chunks_active'), 'chunks', ['is_active'], unique=False, postgresql_where='(is_active = true)')
    op.alter_column('chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               existing_nullable=True)
    # ### end Alembic commands ###
