[project]
name = "assistant-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "mark", email = "mrnikerin@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.115",
    "uvicorn[standard]>=0.32",
    "openai>=1.50.0",
    "sqlalchemy[asyncio]>=2.0",
    "asyncpg>=0.30",
    "pydantic>=2.9",
    "rag-shared"
]

[project.scripts]
assistant-service = "assistant_service:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[tool.uv.sources]
rag-shared = { workspace = true }
